# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "39e3fc3eda0c39b0097c956dd53f0e3e"
name = "Autovariant AI"
application_url = "https://autovariant-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# write_products: Ürün ve varyant oluşturma
# read_locations: Stok için location ID almak
# write_inventory: Stok miktarını ayarlamak
# read_inventory: Mevcut stok bilgisini okumak
scopes = "write_products,read_locations,write_inventory,read_inventory"

[auth]
redirect_urls = [ "https://autovariant-production.up.railway.app/api/auth/callback" ]
